package ai

import (
	"context"
	"fmt"
)

// AnthropicEvaluator implements CodeEvaluator for Anthropic Claude API
// See: https://docs.anthropic.com/claude/reference

type AnthropicEvaluator struct {
	APIKey string
	Model  string
}

func NewAnthropicEvaluator(cfg AIAgentConfig) *AnthropicEvaluator {
	return &AnthropicEvaluator{
		APIKey: cfg.Key,
		Model:  cfg.Model,
	}
}

func (a *AnthropicEvaluator) Evaluate(ctx context.Context, fileName, code string) (*EvaluationResult, error) {
	fmt.Printf("Evaluating %s with Anthropic Claude (model: %s)\n", fileName, a.Model)
	// TODO: Integrate with Anthropic Claude API
	prompt := GetEvaluationPrompt(code)
	fmt.Printf("Evaluating %s with Anthropic Claude (model: %s)\nPrompt: %s\n", fileName, a.Model, prompt)
	// TODO: Integrate with Anthropic Claude API
	return &EvaluationResult{
		File:                       fileName,
		Score:                      78, // Placeholder
		FactoresNoCumple:           []string{"factor-anthropic"},
		ProblemasConcurrencia:      []string{},
		RecomendacionesRefactor:    "Use Claude suggestions.",
		RecomendacionesComentarios: "Add more doc comments.",
		Documentacion:              "Generated by Claude.",
		EvaluacionFunciones:        []FuncionEvaluationResult{},
	}, nil
}
