package ai

import (
	"context"
	"fmt"
)

// CohereEvaluator implements CodeEvaluator for Cohere API
// See: https://docs.cohere.com/reference/overview

type CohereEvaluator struct {
	APIKey string
	Model  string
}

func NewCohereEvaluator(cfg AIAgentConfig) *CohereEvaluator {
	return &CohereEvaluator{
		APIKey: cfg.Key,
		Model:  cfg.Model,
	}
}

func (c *CohereEvaluator) Evaluate(ctx context.Context, fileName, code string) (*EvaluationResult, error) {
	fmt.Printf("Evaluating %s with Cohere (model: %s)\n", fileName, c.Model)
	// TODO: Integrate with Cohere API
	return &EvaluationResult{
		File:                       fileName,
		Score:                      76, // Placeholder
		FactoresNoCumple:           []string{"factor-cohere"},
		ProblemasConcurrencia:      []string{},
		RecomendacionesRefactor:    "Use Cohere suggestions.",
		RecomendacionesComentarios: "Add more doc comments.",
		Documentacion:              "Generated by Cohere.",
		EvaluacionFunciones:        []FuncionEvaluationResult{},
	}, nil
}
