package ai

import (
	"context"
	"fmt"
)

// CopilotEvaluator implements CodeEvaluator for Copilot
type CopilotEvaluator struct {
	APIKey string
	Model  string
}

func NewCopilotEvaluator(cfg AIAgentConfig) *CopilotEvaluator {
	return &CopilotEvaluator{
		APIKey: cfg.Key,
		Model:  cfg.Model,
	}
}

func (c *CopilotEvaluator) Evaluate(ctx context.Context, fileName, code string) (*EvaluationResult, error) {
	prompt := GetEvaluationPrompt(code)
	fmt.Printf("Evaluating %s with Copilot (model: %s)\nPrompt: %s\n", fileName, c.Model, prompt)
	// Simulate a result (replace with actual Copilot response parsing)
	return &EvaluationResult{
		File:                       fileName,
		Score:                      80, // Placeholder
		FactoresNoCumple:           []string{"factor-x"},
		ProblemasConcurrencia:      []string{},
		RecomendacionesRefactor:    "Use Copilot suggestions.",
		RecomendacionesComentarios: "Add more doc comments.",
		Documentacion:              "Generated by Copilot.",
		EvaluacionFunciones:        []FuncionEvaluationResult{},
	}, nil
}
