package ai

import (
	"context"
	"fmt"
)

// GeminiEvaluator implements CodeEvaluator for Google Gemini (Vertex AI) API
// See: https://cloud.google.com/vertex-ai/docs/generative-ai/learn/overview

type GeminiEvaluator struct {
	APIKey string
	Model  string
}

func NewGeminiEvaluator(cfg AIAgentConfig) *GeminiEvaluator {
	return &GeminiEvaluator{
		APIKey: cfg.Key,
		Model:  cfg.Model,
	}
}

func (g *GeminiEvaluator) Evaluate(ctx context.Context, fileName, code string) (*EvaluationResult, error) {
	fmt.Printf("Evaluating %s with Google Gemini (model: %s)\n", fileName, g.Model)
	// TODO: Integrate with Google Gemini API
	return &EvaluationResult{
		File:                       fileName,
		Score:                      77, // Placeholder
		FactoresNoCumple:           []string{"factor-gemini"},
		ProblemasConcurrencia:      []string{},
		RecomendacionesRefactor:    "Use Gemini suggestions.",
		RecomendacionesComentarios: "Add more doc comments.",
		Documentacion:              "Generated by Gemini.",
		EvaluacionFunciones:        []FuncionEvaluationResult{},
	}, nil
}
