package ai

import (
	"context"
	"fmt"
)

// MistralEvaluator implements CodeEvaluator for Mistral API
// See: https://docs.mistral.ai/api/

type MistralEvaluator struct {
	APIKey string
	Model  string
}

func NewMistralEvaluator(cfg AIAgentConfig) *MistralEvaluator {
	return &MistralEvaluator{
		APIKey: cfg.Key,
		Model:  cfg.Model,
	}
}

func (m *MistralEvaluator) Evaluate(ctx context.Context, fileName, code string) (*EvaluationResult, error) {
	fmt.Printf("Evaluating %s with Mistral (model: %s)\n", fileName, m.Model)
	// TODO: Integrate with Mistral API
	return &EvaluationResult{
		File:                       fileName,
		Score:                      74, // Placeholder
		FactoresNoCumple:           []string{"factor-mistral"},
		ProblemasConcurrencia:      []string{},
		RecomendacionesRefactor:    "Use Mistral suggestions.",
		RecomendacionesComentarios: "Add more doc comments.",
		Documentacion:              "Generated by Mistral.",
		EvaluacionFunciones:        []FuncionEvaluationResult{},
	}, nil
}
